### ISSUE TITLE
affichage décalé dans un design

### ISSUE THREAD

**Issue by gienne** [JEALG/JEEDOM-Widget_JAG-doc#1]
l'affichage de temperature ne fonctionne pas correctement dans design, les informations sont affichées en dessous de l'icone et non a coté comma dans le dashboard.

**Expected behavior**
meme affichage dans design que dans dashboard
**Screenshots**

**Desktop (please complete the following information):**
 - windows 10 Pro
 - Browser firefox
 - Version 69.0.1 (64 bits)

**Additional context**
![Annotation 2019-09-29 103408](https://user-images.githubusercontent.com/33548858/65829338-cf2f2c80-e2a4-11e9-8089-d8f3a634e7ec.jpg)

**Comment by JEALG** [comment]
Désolé
je n'avais pas vu ta demande, peut-tu me dire si toujours ok ?
passes plus par le forum pour une question, je saurais plus réactif
Bonne soirée
